import pandas as pd

keywords = [
"hdfc credit card apply offer",
"hdfc credit card apply link",
"hdfc credit card",
"hdfc bank loan on credit card",
"hdfc bank loan on credit card apply",
"hdfc bank credit card loan",
"hdfc credit card loan apply offer",
"hdfc credit card loan",
"hdfc credit card loan apply online",
"Apply HDFC Credit Card loan",
"hdfc bank credit card loan apply",
"credit card loan apply hdfc",
"hdfc credit card loan for everyone",
"hdfc credit card loan apply",
"Loan on hdfc card",
"Apply loan on HDFC credit card",
"HDFC Insta Jumbo Loan",
"Loan on HDFC Card Today",
"instant loan on hdfc credit card",
"Apply Jumbo Loan Instantly",
"HDFC Fast Approval Loan",
"Quick HDFC Loan Apply",
"credit card apply hdfc",
"hdfc credit card for everyone",
"hdfc credit card apply",
"hdfc popular credit cards",
"Best HDFC Credit card",
"hdfc credit card apply now",
"hdfc credit card apply online",
"Apply HDFC Credit Card",
"apply hdfc credit card free",
"apply hdfc bank credit card",
"apply hdfc credit card free link",
"hdfc card apply today link",
"hdfc card apply today",
"hdfc card apply",
"link for hdfc credit card apply",
"hdfc bank loan apply",
"hdfc bank credit card offers",
"Apply for hdfc Credit Card Online",
"hdfc bank credit card loan apply online",
"hdfc credit card apply link online",
"hdfc bank loan on credit card apply",
"hdfc shopping credit card",
"hdfc personal loan",
"hdfc lifetime free credit cards",
"apply hdfc card online from link",
"Hdfc credit card apply karo",
"Hdfc credit card apply link offer",
"apply hdfc card offer",
"hdfc shopping credit card",
"apply hdfc card online",
"apply hdfc card today",
"Submit Your Application Now - HDFC Credit Card Apply",
"apply hdfc free credit card",
"hdfc bank credit card apply",
"hdfc bank credit card for beginners",
"hdfc bank credit apply",
"hdfc bank instant loan apply",
"HDFC Fast Approval Loan",
"hdfc bank jumbo loan",
"hdfc bank jumbo loan credit card",
"hdfc bank credit card jumbo loan",
"hdfc bank credit card jumbo loan",
"hdfc jumbo loan apply",
"hdfc credit card jumbo loan",
"apply hdfc bank credit card loan",
"apply hdfc bank credit card jumbo offer",
"apply hdfc jumbo loan",
"apply hdfc bank jumbo offer",
"hdfc bank card apply",
"hdfc bank card apply online",
"get hdfc bank credit card",
"get card hdfc bank",
"card apply hdfc bank",
"online card apply hdfc bank",
"online atm card apply hdfc bank",
"Hdfc card apply eligibility",
"Hdfc card apply eligibility online",
"hdfc bank loan apply online",
"hdfc card online apply",
"hdfc bank online card apply",
"loan apply hdfc",
"Personal loan apply hdfc",
"HDFC Personal Loan apply online",
"hdfc loan apply now",
"get hdfc card",
"Hdfc bank loan apply online eligibility",
"HDFC-Bank Xpress Loan",
"HDFC xpress personal loan",
"HDFC Bank Credit Card",
"HDFC XPRESS Loan offer",
"apply hdfc loan",
"HDFC Jumbo Loan Apply",
"hdfc jumbo loan offer check",
"loan available hdfc bank",
"hdfc credit apply",
"hdfc credit apply now",
"hdfc bank card",
"choose card hdfc bank",
"apply card hdfc bank",
"get emi card hdfc bank",
"Hdfc emi apply online credit card",
"HDFC Loan apply online",
"HDFC jumbo loan",
"hdfc jumbo personal loan",
"loan by hdfc bank",
"hdfc credit card loan everyone",
"Hdfc credit card eligibility",
"Hdfc credit card eligibility calculator",
"Hdfc credit card on loan",
"HDFC credit card Insta Loan",
"online loan hdfc bank",
"hdfc apply for credit card",
"xpress personal loans hdfc",
"HDFC loan against credit card",
"HDFC low-interest credit card",
"HDFC instant credit card approval",
"insta jumbo loan hdfc",
"hdfc loan",
"hdfc personal loan apply",
"hdfc online loan",
"hdfc credit cards"
]

df = pd.DataFrame({
    "Sno": range(1, len(keywords)+1),
    "keyword": keywords
})

path = "C:\\Users\\sriva\\Downloads\\Bidding\\hdfc_keywords.csv"
df.to_csv(path, index=False)

path